[theme]
primaryColor = "#731E27"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#DAD0D1"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
headless = true
runOnSave = false

[browser]
gatherUsageStats = false